/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_duongtd_scannerdocument_MyNDK */

#ifndef _Included_com_duongtd_scannerdocument_MyNDK
#define _Included_com_duongtd_scannerdocument_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_duongtd_scannerdocument_MyNDK
 * Method:    getNDKString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_duongtd_scannerdocument_MyNDK_getNDKString
  (JNIEnv *, jclass);

/*
 * Class:     com_duongtd_scannerdocument_MyNDK
 * Method:    autoFilter
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_duongtd_scannerdocument_MyNDK_autoFilter
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_duongtd_scannerdocument_MyNDK
 * Method:    cropBitmap
 * Signature: (Landroid/graphics/Bitmap;FFFFFFFF)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_duongtd_scannerdocument_MyNDK_cropBitmap
  (JNIEnv *, jclass, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
